projects:
  msb:
    schemaPath: src/graphql/schema.json
    includes:
      - src/App/API/graphql/**/*.ts
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/App/API/index.ts
        docsFilePath: src/App/API/graphql
        graphQLApiId: n3mkzadxgjdlncm5uv652h3m7a
      endpoints:
        prod: >-
          https://tmyawnbwrzhfzj2k5hqqfi44wq.appsync-api.us-west-2.amazonaws.com/graphql
