// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:b0810fdd-26c8-49f9-9b8b-27ba34c3e942",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_nLtKFjDsH",
    "aws_user_pools_web_client_id": "1qdutc287nqvudn6p385lsuppc",
    "aws_appsync_graphqlEndpoint": "https://tmyawnbwrzhfzj2k5hqqfi44wq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "msb-20190204130453--hostingbucket",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://msb-20190204130453--hostingbucket.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
