// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:0b11b5e0-1045-4ec1-9fbc-a79adb6201c9",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_btmrqnQ4p",
    "aws_user_pools_web_client_id": "68pbel1nt3ej72as2r2kjpfqf8",
    "aws_appsync_graphqlEndpoint": "https://sljheatnszbmzirkpdo4jbmurq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "msb-20190204111049--hostingbucket",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://msb-20190204111049--hostingbucket.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
